### ISSUE TITLE
add more popular addons to the project

### ISSUE THREAD

**Issue by auvipy** [fgimian/flaskage#3]

**Comment by auvipy** [comment]
Flask admin, app builder, classy views to name a few

**Comment by auvipy** [comment]
is the project unmaintained?

**Comment by fgimian** [comment]
I'm sorry but I rarely am developing projects with Flask right now so haven't really worked on this for some time.

**Comment by auvipy** [comment]
any suggestions so I can contribute to make it active?

**Comment by fgimian** [comment]
U

**Comment by fgimian** [comment]
I'd be happy to hand the project over to a new maintainer to continue working on it if interested?

**Comment by auvipy** [comment]
I'm interested :)

**Comment by fgimian** [comment]
@auvipy Thanks for expressing an interest.  Do you have some recent Python code you've written for me to check out?

**Comment by auvipy** [comment]
well I'm the co-maintainer of drf-extension package. It's a popular django rest framework extension. Beside I try to contribute essential opensource python/django projects. My interest in this project is because I want such flask scaffolding to be upgraded and live for long. You could checkout my github activities.

**Comment by fgimian** [comment]
Thanks so much, looks great.  I'll be in touch with you shortly to help you take over the project.  There's a readthedocs page too which I'll need to check how to transfer.

Really appreciate you taking this over as I put a huge amount of work into it and truly feel that there's nothing else out there quite like it for Flask :smile: 

Cheers
Fotis

**Comment by auvipy** [comment]
You are right. And having such a FOSS tool in flask eco system will really save a lot of time for developers. And I really want to revive IT :) my email: auvipy@gmail.com

Thanks for your consideration for the take over :) 

Cheers
Asif

**Comment by fgimian** [comment]
Thanks so much @auvipy, I've just added you as a collaborator to start with and I'll happily do a full transfer to you in the coming weeks to give you some time to settle in.  I'm about to check out what's involved in transferring RTD.

**Comment by fgimian** [comment]
Ok, RTD is very easy.  Can you please create an account on https://readthedocs.org/ and provide me your username?  Thanks so much! :smile:

**Comment by fgimian** [comment]
P.S.: Please also let me know if you can access and control the Travis CI page here https://travis-ci.org/fgimian/flaskage

**Comment by auvipy** [comment]
yes I can :) and thanks a lot. my rtd is auvipy

**Comment by fgimian** [comment]
Thanks buddy, I've just added you as a maintainer on RTD, please let me know if you can now see Flaskage in your project list :smile:

**Comment by auvipy** [comment]
yes I can see :D

**Comment by fgimian** [comment]
Awesome mate.  I'll give you some time to get settled in.  Feel free to ask any questions you have here or you can find my email address in the commit history :smile:

**Comment by auvipy** [comment]
no worry buddy take your time and lemme settle down for a while :dancers:

**Comment by fgimian** [comment]
@auvipy Hi there, just wondering if you intend to work on this project in the near future?

**Comment by auvipy** [comment]
yes I will. was busy with some personal sprint :)

**Comment by fgimian** [comment]
@auvipy It seems that you are also too busy to work on this project.  As such, I'm opening this up to any other maintainers who are interested.
